### PR TITLE
Add VLC support, and bug fixes

### PR DESCRIPTION
**Pull request by jgabriel98**
-  added support for VLC player.

- Also fixed a bug in `./conky/npart.lua` script, where it loaded all active players art image.
So if you had _spotify_ and _cmus_ open, it would show **Spotify**'s song data (name and artist), but **cmus** image art.

- i've also refactored some of the code for better readability, but with no logical changes.

### CODE REVIEW

**Comment by foxfirecodes** [comment]
just taking a preliminary read over (I'm in mobile so will review properly when I'm back on my desktop), and I'm curious -- how does this solve the issue of multiple players being open? for all 3 players it appears we are still only checking that they're open/running in npart.lua, not that they're actively in a playing state, or that they were the last player to be in a playing state (but may now be paused)

**Comment by jgabriel98** [comment]
> just taking a preliminary read over (I'm in mobile so will review properly when I'm back on my desktop), and I'm curious -- how does this solve the issue of multiple players being open? for all 3 players it appears we are still only checking that they're open/running in npart.lua, not that they're actively in a playing state, or that they were the last player to be in a playing state (but may now be paused)

in the npart.lua script, we had the following code logic before:
```
${if_running spotify}${exec ./scripts/fetch-art spotify}
	${image ./data/spotify.png -p 0,0 -s 125x125 -n}
${endif}
${if_match "" != "${exec playerctl -p vlc status}"}${exec ./scripts/fetch-art vlc}
	${image ./data/vlc.png -p 0,0 -s 125x125 -n}
${endif}
${if_running cmus}${exec ./scripts/fetch-art cmus}
	${image ./data/cmus.png -p 0,0 -s 125x125 -n}
${endif}
```

**So, it checked for every player, and if it was playing, then it would update the _art_.
So it means that the last active player (paused or not) would overwritte the _art_ image.**

note that the logic for checking active players in `npart.lua` is different from the `np.lua`, where the _npart.lua_ reaches all `${if_}` (it uses a bunch of "if ... if... if ..."), but the _np.lua_ only enters one ${if_} (because it uses chained if-else-if-else-... logic like)





now we have this new code logic:
```
${if_running spotify}${exec ./scripts/fetch-art spotify}
	${image ./data/spotify.png -p 0,0 -s 125x125 -n}
${else}${if_match "" != "${exec playerctl -p vlc status}"}${exec ./scripts/fetch-art vlc}
	${image ./data/vlc.png -p 0,0 -s 125x125 -n}
${else}${if_running cmus}${exec ./scripts/fetch-art cmus}
	${image ./data/cmus.png -p 0,0 -s 125x125 -n}
${endif}
${endif}
${endif}
```

now it follows the same if-else logic from `np.lua` script, where it enters only one active player (the first one), because the logic now uses chained if-else s

**Review by foxfirecodes — APPROVED** [review]
thanks for the explanation, finally got a chance to review this while on an actual computer! looks good to me, although I want to leave this with some final thoughts which will some day maybe make their way into the codebase in the form of a commit on my part:

1. there's way too much duplication of "if player X, do Y" across the np.lua, npart.lua, and shell scripts. realistically, there should just be simple `is-player-running.sh`, `get-player-metadata.sh` and `fetch-current-art.sh` scripts which all handle finding the current player in an intelligent and central way, and then the conky scripts don't need to rely on the terrible if/else/elif support of conky.
2. good god I forgot how bad the clock is. i really really really should turn that into a shell script. with some real math. not this current monstrosity.
3. conky's conditional logic is just overall bad and we should really only have one usage of it: is a player running? show the player stuff. no? show the clock.
4. while this will now show only one album art at a time and not get as confusing, this does still have the problem of not respecting WHICH player is currently playing -- if I understand the ordering correctly, if I had spotify and cmus open and was playing music in cmus, since spotify is the first conditional, it would try and show art from spotify despite cmus being the one playing. the solution to this is non-trivial since it isn't as simple as showing the currently playing player; you also have to know what was the most *recently* playing player, since once you pause your music, it has to go off of the past to determine what one you want to see info for.
5. all 3 of spotify, vlc, and cmus need the same metadata (album, artist, title, & URL), but both spotfiy and vlc even get it from the same location: playerctl. therefore, abstracting this behavior in a way that allows the simplification and support of all players using a shared source like playerctl, as well as supporting alternative sources like cmus-remote, but keeping the rest of the logic the same would be optimal so that conky need not know a thing about where its source is coming from.

anyways, thanks for submitting this, and hopefully this is the first step in even further simplifying these scripts to eventually support an even vaster plethora of music sources :) 

(you're welcome to merge whenever you're ready)

**Comment by jgabriel98** [comment]
> (you're welcome to merge whenever you're ready)

I don't have write permission to your repository... 
:/
So you can merge it,
or you can give me write permissions (which i don't think is a very safe solution)

**Comment by foxfirecodes** [comment]
odd, I thought me approving it gave you the ability to merge. perhaps I have something misconfigured. I'll merge it now, thanks!

**Comment by jgabriel98** [comment]
> 4. while this will now show only one album art at a time and not get as confusing, this does still have the problem of not respecting WHICH player is currently playing -- if I understand the ordering correctly, if I had spotify and cmus open and was playing music in cmus, since spotify is the first conditional, it would try and show art from spotify despite cmus being the one playing. the solution to this is non-trivial since it isn't as simple as showing the currently playing player; you also have to know what was the most recently playing player, since once you pause your music, it has to go off of the past to determine what one you want to see info for.

For that, the following logic would solve it:

inside the conky main loop (the main 1sec loop):
1. run though playerctl playerList, and get each player playing status (playing, stopped or paused)
2. compare those status to their previous status, something like this:  spotify_prev_status != spotify_current_status
3. if the status had changed, use this player as the _active one_ for conky 'now playing'
if not, keep the old _active one_ player

note: the step which runs through the players comparing it status, can be done in a chained 'if else', since it is **very** unlileky to the user use more than one player at the same second interval.


This is just a suggestion that came to my mind when reading your post, maybe there's a better way to solve it, but i think this should be enought.

**Comment by foxfirecodes** [comment]
i think actually the best way to do this, building off of the player-agnostic idea, would be to do what you suggested except in step #2 instead of comparing a previous & current status for each individual player, we just have a file with a "last playing player" stored in it. this gets updated any time that value changes. then in all the other metadata/art scripts, all they have to do is fetch the last playing player, see if it's still playing, and if so fetches the metadata/art

but yeah I think that's the general idea, you're welcome to contribute this if you would like otherwise I might try and tackle this in the upcoming weekend :)

**Pull request merged**
